services:
  - type: web
    name: memorymap-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: |
      cd backend
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: POSTGRES_USER
        fromDatabase:
          name: memorymap-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: memorymap-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: memorymap-db
          property: database
      - key: POSTGRES_HOST
        fromDatabase:
          name: memorymap-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: memorymap-db
          property: port
      - key: SECRET_KEY
        generateValue: true
      - key: HUGGINGFACE_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
    autoDeploy: true

databases:
  - name: memorymap-db
    databaseName: memorymap
    user: memorymap_user
    region: oregon
    plan: starter

  - type: redis
    name: memorymap-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru 